version: 2

updates:
  # GitHub Actions - all updates including major
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Asia/Kolkata"
    labels:
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
