name: Flutter Android App Setup

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup-flutter-app:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: clear Flutter
      - run: |
          cd action
          rm - rf *
          
      
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: Initialize Flutter Android app structure"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions <github-actions[bot]@users.noreply.github.com>"
