name: Flutter Android App Setup

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup-flutter-app:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Verify Flutter version
        run: flutter --version
      
      - name: Create Flutter Android app
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "Creating new Flutter Android app..."
            flutter create --project-name my_app --org com.2f1b08e --platforms android .
          else
            echo "Flutter app already exists"
          fi
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run Flutter analyze
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
      
      - name: Build Android APK
        run: flutter build apk --release
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Initialize Flutter Android app structure"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions <github-actions[bot]@users.noreply.github.com>"
