name: Create Dependabot Labels

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
    paths:
      - '.github/workflows/create-labels.yml'

jobs:
  create-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    env:
      LABELS_JSON: |
        [
          {"name": "dependencies", "color": "0366d6", "description": "Pull requests that update a dependency file"},
          {"name": "automated", "color": "1d76db", "description": "Automated updates"},
          {"name": "auto-update", "color": "0e8a16", "description": "Automatic dependency updates"},
          
          {"name": "gradle", "color": "02303a", "description": "Pull requests that update Gradle dependencies"},
          {"name": "java", "color": "b07219", "description": "Pull requests that update Java code or dependencies"},
          {"name": "android", "color": "3ddc84", "description": "Pull requests that update Android dependencies"},
          {"name": "kotlin", "color": "A97BFF", "description": "Pull requests that update Kotlin dependencies"},
          
          {"name": "npm", "color": "cb3837", "description": "Pull requests that update npm dependencies"},
          {"name": "javascript", "color": "f1e05a", "description": "Pull requests that update JavaScript code or dependencies"},
          {"name": "typescript", "color": "3178c6", "description": "Pull requests that update TypeScript code or dependencies"},
          
          {"name": "github-actions", "color": "2088FF", "description": "Pull requests that update GitHub Actions workflows"},
          {"name": "ci-cd", "color": "1f6feb", "description": "Continuous integration and deployment updates"},
          
          {"name": "docker", "color": "0db7ed", "description": "Pull requests that update Docker dependencies"},
          {"name": "python", "color": "3572A5", "description": "Pull requests that update Python code or dependencies"},
          {"name": "pip", "color": "3776ab", "description": "Pull requests that update pip dependencies"},
          {"name": "rust", "color": "dea584", "description": "Pull requests that update Rust dependencies"},
          
          {"name": "security", "color": "d73a4a", "description": "Security vulnerability fixes"},
          {"name": "major", "color": "d93f0b", "description": "Major version updates"},
          {"name": "minor", "color": "fbca04", "description": "Minor version updates"},
          {"name": "patch", "color": "0e8a16", "description": "Patch version updates"}
        ]
    
    steps:
      - name: Create or update labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = JSON.parse(process.env.LABELS_JSON);
            
            for (const label of labels) {
              try {
                // Try to create the label
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  description: label.description || '',
                  color: label.color
                });
                console.log(`✅ Created label: ${label.name}`);
              } catch (error) {
                if (error.status === 422) {
                  // Label already exists, update it
                  try {
                    await github.rest.issues.updateLabel({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      name: label.name,
                      description: label.description || '',
                      color: label.color
                    });
                    console.log(`🔄 Updated existing label: ${label.name}`);
                  } catch (updateError) {
                    console.error(`❌ Error updating label '${label.name}': ${updateError.message}`);
                  }
                } else {
                  console.error(`❌ Error creating label '${label.name}': ${error.message}`);
                }
              }
            }
            
            console.log('
🎉 Label creation/update complete!');
