name: Create Dependabot Labels

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/create-labels.yml'

jobs:
  create-labels:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create all Dependabot labels
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          # Core dependency labels
          gh label create "dependencies" --repo "$REPO" --color "0366d6" --description "Pull requests that update a dependency file" --force || true
          gh label create "automated" --repo "$REPO" --color "1d76db" --description "Automated updates" --force || true
          gh label create "auto-update" --repo "$REPO" --color "0e8a16" --description "Automatic dependency updates" --force || true
          
          # Gradle/Java/Android
          gh label create "gradle" --repo "$REPO" --color "02303a" --description "Pull requests that update Gradle dependencies" --force || true
          gh label create "java" --repo "$REPO" --color "b07219" --description "Pull requests that update Java code or dependencies" --force || true
          gh label create "android" --repo "$REPO" --color "3ddc84" --description "Pull requests that update Android dependencies" --force || true
          gh label create "kotlin" --repo "$REPO" --color "A97BFF" --description "Pull requests that update Kotlin dependencies" --force || true
          
          # npm/JavaScript/TypeScript
          gh label create "npm" --repo "$REPO" --color "cb3837" --description "Pull requests that update npm dependencies" --force || true
          gh label create "javascript" --repo "$REPO" --color "f1e05a" --description "Pull requests that update JavaScript code or dependencies" --force || true
          gh label create "typescript" --repo "$REPO" --color "3178c6" --description "Pull requests that update TypeScript code or dependencies" --force || true
          
          # GitHub Actions & CI/CD
          gh label create "github-actions" --repo "$REPO" --color "2088FF" --description "Pull requests that update GitHub Actions workflows" --force || true
          gh label create "ci-cd" --repo "$REPO" --color "1f6feb" --description "Continuous integration and deployment updates" --force || true
          
          # Other ecosystems
          gh label create "docker" --repo "$REPO" --color "0db7ed" --description "Pull requests that update Docker dependencies" --force || true
          gh label create "python" --repo "$REPO" --color "3572A5" --description "Pull requests that update Python code or dependencies" --force || true
          gh label create "pip" --repo "$REPO" --color "3776ab" --description "Pull requests that update pip dependencies" --force || true
          gh label create "rust" --repo "$REPO" --color "dea584" --description "Pull requests that update Rust dependencies" --force || true
          
          # Version type labels
          gh label create "security" --repo "$REPO" --color "d73a4a" --description "Security vulnerability fixes" --force || true
          gh label create "major" --repo "$REPO" --color "d93f0b" --description "Major version updates" --force || true
          gh label create "minor" --repo "$REPO" --color "fbca04" --description "Minor version updates" --force || true
          gh label create "patch" --repo "$REPO" --color "0e8a16" --description "Patch version updates" --force || true
          
          echo "✅ All labels created/updated successfully!"
