name: Build LocalSend APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout LocalSend Repository
        uses: actions/checkout@v5
        with:
          repository: localsend/localsend
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          cache: true
          
      - name: Verify Flutter Installation
        run: flutter doctor -v
        
      - name: Install Flutter Dependencies
        working-directory: ./app
        run: flutter pub get
        
      - name: Build APK
        working-directory: ./app
        run: flutter build apk
        
      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: localsend-release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 30
