name: Build Pixel-Play

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
         repository: 2f1b08e/PixelPlay
      
      
      
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: 17
          check-latest: true
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew assemble
      
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: PixelPlay-Debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: ignore
      
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: pixelplay-release-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: ignore
      
