name: Purge non-dotfiles

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/purge-non-dotfiles.yml"

permissions:
  contents: write

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Delete everything except dotfiles
        shell: bash
        run: |
          set -euo pipefail
          shopt -s dotglob nullglob
          # Build list: all entries except those starting with '.' (dotfiles/dirs)
          to_delete=()
          for p in *; do
            # With dotglob enabled above, '*' includes dotfiles; exclude those explicitly
            [[ "$(basename "$p")" == .* ]] && continue
            to_delete+=("$p")
          done
          # Safety: no-op if nothing to delete
          if (( ${#to_delete[@]} )); then
            rm -rf -- "${to_delete[@]}"
          fi
          # Optionally also remove tracked files that may now be missing from index (clean staging)
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Purge all non-dotfiles"
            git push
          else
            echo "No changes to commit."
          fi
